##
# Server
##
server:
    port: 8081
    servlet:
        context-path: /oauth2-gestao-funcionario-microservice


feign:
    client:
        config:
            funcionarioClient:
                LoggerLevel: full


logging.level.br.com.zup.edu.gestaofuncionarioclient.client.FuncionariosClient: DEBUG


##
# Client Credentials Flow
##

spring:
    security:
        oauth2:
            client:
                registration:
                    funcionarios:
                        client-id: oauth2-gestao-funcionario-microservice
                        client-secret: kJ56YuXnPA6Ul59DpDnhw3S6M9a5tfiC
                        authorization-grant-type: client_credentials
                        scope: funcionarios:read
                provider:
                    funcionarios:
                        token-uri: http://localhost:18080/realms/gestao-funcionarios/protocol/openid-connect/token